{
 "title": "Logs",
 "tags": [
  "Logs",
  "Logging"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Spring Admin",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{application=\"spring-admin\"} | logfmt ",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "Service Registry",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{application=\"service-registry\"} !~ `org.zalando.logbook.Logbook`",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "API Gateway",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{application=\"api-gateway\"} | logfmt",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "Auth Service",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{application=\"auth-service\"} !~ `org.zalando.logbook.Logbook`",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "Order Service",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{application=\"order-service\"} !~ `org.zalando.logbook.Logbook`",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "Ticker Service",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "{application=\"ticker-service\"} !~ `org.zalando.logbook.Logbook`",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "Producer",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "{application=\"producer-service\"} !~ `org.zalando.logbook.Logbook`",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "Consumer",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "{application=\"consumer\"} !~ `org.zalando.logbook.Logbook`",
     "maxLines": 10
    }
   ]
  }
 ]
}