{
 "title": "HTTP Logs Test",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": {}
   },
   { "name": "filter", "label": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "HTTP Requests",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{application=\"$application\"} |= `org.zalando.logbook.Logbook` |~ `$filter` | regexp `(?P<json_part>\\{.*:.*)` | line_format `{{.json_part}}` | json | uri =~ `.+`",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "HTTP Requests With Status",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{application=\"$application\"} |= `org.zalando.logbook.Logbook` |~ `$filter` | regexp `(?P<json_part>\\{.*:.*)` | line_format `{{.json_part}}` | json | status =~ `.+`",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "API Access",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by(URL) (count_over_time({application=\"$application\"} |= `org.zalando.logbook.Logbook` |~ `$filter` !~ `/actuator` | regexp `(?P<json_part>\\{.*:.*)` | line_format `{{.json_part}}` | json | uri =~ `.+` | label_format params=json_part | json URL=\"path\" [$__auto]))",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "Test",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{application=\"$application\"} |= `org.zalando.logbook.Logbook` |~ `$filter` | regexp `(?P<json_part>\\{.*:.*)` | line_format `{{.json_part}}` | label_format params=json_part | json | line_format \"{{.correlation}}\"",
     "maxLines": 10
    }
   ]
  }
 ]
}