{
 "title": "HTTP Stats",
 "tags": [
  "HTTP",
  "API",
  "Performance",
  "Latency",
  "Throughput"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "App", "query": { "query": "label_values(instance)" } },
   {
    "name": "url",
    "label": "URL",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{instance=\"$application\"},uri)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latency for app: \"$application\" and URL: $url",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1.00, sum(rate(http_server_requests_seconds_bucket{instance=~\"$application\", uri=~\"$url\"}[$__rate_interval])) by (le))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{instance=~\"$application\", uri=~\"$url\"}[$__rate_interval])) by (le))",
     "legendFormat": "tp99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{application=~\"$application\", uri=~\"$uri\"}[$__rate_interval])) by (le))",
     "legendFormat": "tp95"
    }
   ]
  },
  {
   "title": "Throughput for app: \"$application\" and URL: $url",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=~\"$application\", uri=~\"$url\"}[$__rate_interval])) by (outcome)",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Latency heatmap for app: \"$application \" and URL: $url",
   "type": "heatmap",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_bucket{instance=~\"$application\", uri=~\"$url\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}