apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-svc
  labels:
    app: kafka-ui
    name: kafka-ui
spec:
  selector:
    app: kafka-ui
    name: kafka-ui
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
      name: tcp-8080