apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  labels:
    app: kafka
    name: kafka
spec:
  selector:
    app: kafka
    name: kafka
  type: NodePort
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 32092
      name: kafka-broker