apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    app: postgres
    name: postgres
spec:
  selector:
    app: postgres
    name: postgres
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 32432
      name: postgres-host